Repository PH-DC/phdc-discord-bot, pull requests merged in 2021-04, with the labels that each got.

#4 Add new event's and delete a particular event
  main.py
Labels: enhancement

#7 Fix Event Command
  .env
  main.py
Labels: bug, enhancement

#8 Event Synatx
  main.py
Labels: documentation, enhancement

#11 Added the dynamic project feature
  main.py
Labels: enhancement

#12 Updated
  main.py
Labels: enhancement, good first issue

#15 Added GitHub search
  main.py
Labels: enhancement
